# Generated by Django 5.2.6 on 2025-10-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_services_user_id_4ca160_idx',
            old_name='ai_services_user_service_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_services_created_e214ea_idx',
            old_name='ai_services_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedcontent',
            new_name='ai_services_content_33bd52_idx',
            old_name='ai_services_content_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedcontent',
            new_name='ai_services_user_id_3d63ef_idx',
            old_name='ai_services_user_created_idx',
        ),
    ]
